//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenFuryKMS.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenFuryKMS.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string aboutLbl {
            get {
                return ResourceManager.GetString("aboutLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate!.
        /// </summary>
        internal static string activateBtn {
            get {
                return ResourceManager.GetString("activateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Activation.
        /// </summary>
        internal static string actTitleLbl {
            get {
                return ResourceManager.GetString("actTitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string homeBtn {
            get {
                return ResourceManager.GetString("homeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string infoBtn {
            get {
                return ResourceManager.GetString("infoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please note that this program is provided without warranty. I am not responsible for any misuse that may occur.
        ///I keep track of the status of KMS servers and will update the list as new ones are closed or opened.
        ///It is recommended to use servers marked as &quot;UNSTABLE&quot; only as a last resort, as their operation may be unstable. If these servers stop working permanently, I will remove them from the list and record them in the program documentation as a history..
        /// </summary>
        internal static string infoLbl {
            get {
                return ResourceManager.GetString("infoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product Information.
        /// </summary>
        internal static string infoTitleLbl {
            get {
                return ResourceManager.GetString("infoTitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This program allows you to activate the Home, Pro, Education and Enterprise editions of Windows 10 and 11, as well as Office 2021, 365, 2019, 2016 and 2013.
        ///We use KMS activation, which gives you a license with a duration of 180 days. In most cases, the license renews automatically. If not, you can renew it manually using the &quot;Renew&quot; method.
        ///You can also use the &quot;Rearm&quot; method to get a trial license with a limit of &quot;rearms&quot;.
        ///To use this program you need an internet connection. Without internet, you will  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string insLbl {
            get {
                return ResourceManager.GetString("insLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructions.
        /// </summary>
        internal static string insTitleLbl {
            get {
                return ResourceManager.GetString("insTitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KMS Servers.
        /// </summary>
        internal static string kmsLbl {
            get {
                return ResourceManager.GetString("kmsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Language.
        /// </summary>
        internal static string langLbl {
            get {
                return ResourceManager.GetString("langLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your License.
        /// </summary>
        internal static string licenceDrop {
            get {
                return ResourceManager.GetString("licenceDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licensed.
        /// </summary>
        internal static string Licensed {
            get {
                return ResourceManager.GetString("Licensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licenses.
        /// </summary>
        internal static string licensesLbl {
            get {
                return ResourceManager.GetString("licensesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your Activation Method.
        /// </summary>
        internal static string methodDrop {
            get {
                return ResourceManager.GetString("methodDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activation Method.
        /// </summary>
        internal static string methodLbl {
            get {
                return ResourceManager.GetString("methodLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Note: The license expires in 180 days and is automatically renewed 7 days later, in the rare case If it
        ///doesn&apos;t, press the RENEW button..
        /// </summary>
        internal static string noteLbl {
            get {
                return ResourceManager.GetString("noteLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your Office version.
        /// </summary>
        internal static string officeDrop {
            get {
                return ResourceManager.GetString("officeDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your version of Office is not compatible or is not installed.
        /// </summary>
        internal static string officeError {
            get {
                return ResourceManager.GetString("officeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to create a task that renews the Office license?.
        /// </summary>
        internal static string officeMsgText {
            get {
                return ResourceManager.GetString("officeMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have detected that you are using an incompatible version of Office or it is not installed.
        /// </summary>
        internal static string officeWarning {
            get {
                return ResourceManager.GetString("officeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operating System: .
        /// </summary>
        internal static string osLbl {
            get {
                return ResourceManager.GetString("osLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have detected that you are using an incompatible version of Windows.
        /// </summary>
        internal static string osWarning {
            get {
                return ResourceManager.GetString("osWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your Windows Edition.
        /// </summary>
        internal static string productDrop {
            get {
                return ResourceManager.GetString("productDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        internal static string productsLbl {
            get {
                return ResourceManager.GetString("productsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Key.
        /// </summary>
        internal static string removeBtn {
            get {
                return ResourceManager.GetString("removeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Renew Tasks.
        /// </summary>
        internal static string renewLbl {
            get {
                return ResourceManager.GetString("renewLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your KMS Server.
        /// </summary>
        internal static string serverDrop {
            get {
                return ResourceManager.GetString("serverDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string settingsBtn {
            get {
                return ResourceManager.GetString("settingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a License Status: .
        /// </summary>
        internal static string statusLbl {
            get {
                return ResourceManager.GetString("statusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Information.
        /// </summary>
        internal static string sysInfoLbl {
            get {
                return ResourceManager.GetString("sysInfoLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The task has been successfully created. It will be executed in 182 days..
        /// </summary>
        internal static string taskCreated {
            get {
                return ResourceManager.GetString("taskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a License Renewal.
        /// </summary>
        internal static string taskMsgTitle {
            get {
                return ResourceManager.GetString("taskMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The task and file have been successfully deleted..
        /// </summary>
        internal static string taskRemoved {
            get {
                return ResourceManager.GetString("taskRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlicensed.
        /// </summary>
        internal static string Unlicensed {
            get {
                return ResourceManager.GetString("Unlicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check Updates.
        /// </summary>
        internal static string updatesBtn {
            get {
                return ResourceManager.GetString("updatesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updates.
        /// </summary>
        internal static string updatesLbl {
            get {
                return ResourceManager.GetString("updatesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version: .
        /// </summary>
        internal static string versionLbl {
            get {
                return ResourceManager.GetString("versionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , you will still be able to use OpenFuryKMS but with limited features..
        /// </summary>
        internal static string warning2 {
            get {
                return ResourceManager.GetString("warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string warningText {
            get {
                return ResourceManager.GetString("warningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to create a task that renews the Windows license?.
        /// </summary>
        internal static string winMsgText {
            get {
                return ResourceManager.GetString("winMsgText", resourceCulture);
            }
        }
    }
}
